services:
  online-app:
    build:
      context: .
      Dockerfile: 'Dockerfile-multi'
    ports:
      - "5173:5173"
    networks:
      - my-net
    container_name: online-app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    networks:
      - my-net

networks:
  my-net:
